name: React app deployement

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Install dependencies
      run: npm ci

    - name: Generate version info
      run: |
        VERSION=$(node -p "require('./package.json').version")
        COMMIT_HASH=${GITHUB_SHA}
        BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")
        echo "REACT_APP_VERSION=$VERSION" >> .env.local
        echo "REACT_APP_COMMIT_HASH=$COMMIT_HASH" >> .env.local
        echo "REACT_APP_BUILD_DATE=$BUILD_DATE" >> .env.local
        echo "✅ Version info generated for CI: v$VERSION, commit ${COMMIT_HASH:0:7}, $BUILD_DATE"

    - name: Build
      run: npm run build
      env:
        CI: false

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4