name: React app deployement

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Install dependencies
      run: npm ci

    - name: Set version environment variables
      run: |
        echo "REACT_APP_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
        echo "REACT_APP_COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV
        echo "REACT_APP_BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")" >> $GITHUB_ENV

    - name: Build
      run: npm run build
      env:
        CI: false

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4